version: '3'

services:
  houdini:
    working_dir: /app
    build: .
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - ./:/app/
      - go-modules:/go/pkg/mod
    ports:
      - "8086:8086"
    extra_hosts:
      - "host.docker.internal:host-gateway"


  db:
    image: postgres:13.8-alpine
    container_name: houdini-db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: houdini
    ports:
      - "5437:5432"
    volumes:
      - HOUDINI:/var/lib/postgresql/data


volumes:
  go-modules:
  HOUDINI: