// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dilly3/houdini/internal/storage (interfaces: IStore)
//
// Generated by this command:
//
//	mockgen -destination=api/server/mocks/store_mock.go -package=mocks github.com/dilly3/houdini/internal/storage IStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/dilly3/houdini/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIStore is a mock of IStore interface.
type MockIStore struct {
	ctrl     *gomock.Controller
	recorder *MockIStoreMockRecorder
}

// MockIStoreMockRecorder is the mock recorder for MockIStore.
type MockIStoreMockRecorder struct {
	mock *MockIStore
}

// NewMockIStore creates a new mock instance.
func NewMockIStore(ctrl *gomock.Controller) *MockIStore {
	mock := &MockIStore{ctrl: ctrl}
	mock.recorder = &MockIStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStore) EXPECT() *MockIStoreMockRecorder {
	return m.recorder
}

// GetCommitByID mocks base method.
func (m *MockIStore) GetCommitByID(arg0 context.Context, arg1 string) (*model.CommitInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitByID", arg0, arg1)
	ret0, _ := ret[0].(*model.CommitInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitByID indicates an expected call of GetCommitByID.
func (mr *MockIStoreMockRecorder) GetCommitByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitByID", reflect.TypeOf((*MockIStore)(nil).GetCommitByID), arg0, arg1)
}

// GetCommitsByRepoName mocks base method.
func (m *MockIStore) GetCommitsByRepoName(arg0 context.Context, arg1 string, arg2 int) ([]model.CommitInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitsByRepoName", arg0, arg1, arg2)
	ret0, _ := ret[0].([]model.CommitInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitsByRepoName indicates an expected call of GetCommitsByRepoName.
func (mr *MockIStoreMockRecorder) GetCommitsByRepoName(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitsByRepoName", reflect.TypeOf((*MockIStore)(nil).GetCommitsByRepoName), arg0, arg1, arg2)
}

// GetRepoByID mocks base method.
func (m *MockIStore) GetRepoByID(arg0 context.Context, arg1 string) (*model.RepoInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepoByID", arg0, arg1)
	ret0, _ := ret[0].(*model.RepoInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepoByID indicates an expected call of GetRepoByID.
func (mr *MockIStoreMockRecorder) GetRepoByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepoByID", reflect.TypeOf((*MockIStore)(nil).GetRepoByID), arg0, arg1)
}

// GetRepoByName mocks base method.
func (m *MockIStore) GetRepoByName(arg0 context.Context, arg1 string) (*model.RepoInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepoByName", arg0, arg1)
	ret0, _ := ret[0].(*model.RepoInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepoByName indicates an expected call of GetRepoByName.
func (mr *MockIStoreMockRecorder) GetRepoByName(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepoByName", reflect.TypeOf((*MockIStore)(nil).GetRepoByName), arg0, arg1)
}

// GetReposByLanguage mocks base method.
func (m *MockIStore) GetReposByLanguage(arg0 context.Context, arg1 string, arg2 int) ([]model.RepoInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReposByLanguage", arg0, arg1, arg2)
	ret0, _ := ret[0].([]model.RepoInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReposByLanguage indicates an expected call of GetReposByLanguage.
func (mr *MockIStoreMockRecorder) GetReposByLanguage(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReposByLanguage", reflect.TypeOf((*MockIStore)(nil).GetReposByLanguage), arg0, arg1, arg2)
}

// GetReposByStarCount mocks base method.
func (m *MockIStore) GetReposByStarCount(arg0 context.Context, arg1 int) ([]model.RepoInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReposByStarCount", arg0, arg1)
	ret0, _ := ret[0].([]model.RepoInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReposByStarCount indicates an expected call of GetReposByStarCount.
func (mr *MockIStoreMockRecorder) GetReposByStarCount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReposByStarCount", reflect.TypeOf((*MockIStore)(nil).GetReposByStarCount), arg0, arg1)
}

// SaveCommit mocks base method.
func (m *MockIStore) SaveCommit(arg0 context.Context, arg1 *model.CommitInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCommit", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCommit indicates an expected call of SaveCommit.
func (mr *MockIStoreMockRecorder) SaveCommit(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCommit", reflect.TypeOf((*MockIStore)(nil).SaveCommit), arg0, arg1)
}

// SaveCommits mocks base method.
func (m *MockIStore) SaveCommits(arg0 context.Context, arg1 []model.CommitInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCommits", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCommits indicates an expected call of SaveCommits.
func (mr *MockIStoreMockRecorder) SaveCommits(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCommits", reflect.TypeOf((*MockIStore)(nil).SaveCommits), arg0, arg1)
}

// SaveRepo mocks base method.
func (m *MockIStore) SaveRepo(arg0 context.Context, arg1 *model.RepoInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRepo", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRepo indicates an expected call of SaveRepo.
func (mr *MockIStoreMockRecorder) SaveRepo(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRepo", reflect.TypeOf((*MockIStore)(nil).SaveRepo), arg0, arg1)
}
